get_filename_component(CLIENTCOMMON_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

file(GLOB_RECURSE CLIENTCOMMON_SOURCES CONFIGURE_DEPENDS
    "${CLIENTCOMMON_ROOT}/*.cpp"
    "${CLIENTCOMMON_ROOT}/*.h"
    "${CLIENTCOMMON_ROOT}/*.hpp"
)

file(GLOB_RECURSE CLIENTCOMMON_COMPILE_SOURCES CONFIGURE_DEPENDS
    "${CLIENTCOMMON_ROOT}/*.cpp"
)

list(FILTER CLIENTCOMMON_SOURCES EXCLUDE REGEX ".*/tests/.*")
list(FILTER CLIENTCOMMON_SOURCES EXCLUDE REGEX ".*/cmake/.*")
list(FILTER CLIENTCOMMON_COMPILE_SOURCES EXCLUDE REGEX ".*/tests/.*")
list(FILTER CLIENTCOMMON_COMPILE_SOURCES EXCLUDE REGEX ".*/cmake/.*")
list(FILTER CLIENTCOMMON_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
list(FILTER CLIENTCOMMON_COMPILE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
