get_filename_component(CLIENTCOMMON_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(CLIENTCOMMON_SRC_DIR "${CLIENTCOMMON_ROOT}/src")
set(CLIENTCOMMON_TESTS_DIR "${CLIENTCOMMON_ROOT}/tests")

file(GLOB_RECURSE CLIENTCOMMON_SOURCES CONFIGURE_DEPENDS
    "${CLIENTCOMMON_SRC_DIR}/*.cpp"
    "${CLIENTCOMMON_SRC_DIR}/*.h"
    "${CLIENTCOMMON_SRC_DIR}/*.hpp"
)

file(GLOB_RECURSE CLIENTCOMMON_COMPILE_SOURCES CONFIGURE_DEPENDS
    "${CLIENTCOMMON_SRC_DIR}/*.cpp"
)
list(FILTER CLIENTCOMMON_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
list(FILTER CLIENTCOMMON_COMPILE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")

