get_filename_component(SYSPILOT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(SYSPILOT_SRC_DIR "${SYSPILOT_ROOT}/src")
set(SYSPILOT_TESTS_DIR "${SYSPILOT_ROOT}/tests")

file(GLOB_RECURSE SYSPILOT_SOURCES CONFIGURE_DEPENDS
    "${SYSPILOT_SRC_DIR}/*.cpp"
    "${SYSPILOT_SRC_DIR}/*.h"
    "${SYSPILOT_SRC_DIR}/*.hpp"
)

file(GLOB_RECURSE SYSPILOT_COMPILE_SOURCES CONFIGURE_DEPENDS
    "${SYSPILOT_SRC_DIR}/*.cpp"
)
list(FILTER SYSPILOT_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
list(FILTER SYSPILOT_COMPILE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")

